# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Unit Tests on Ubuntu-Latest
run-name: ${{ github.actor }} Unit Testing on Ubuntu-Latest
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: [self-hosted, linux]
    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: |
        python -V
        echo 3.10
        ls 
        ./install/Linux.sh 3.10
    - name: Unit Testing
      run: |
        ./test.sh

