name: Unit Tests on MacOs-Latest
run-name: ${{ github.actor }} Unit Testing on MacOs-Latest
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build310:
    runs-on: [self-hosted, macos]
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        ./install/MacOs.sh 3.10
    - name: Unit Testing
      run: |
        ./test.sh

  build311:
    runs-on: [self-hosted, macos]
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: |
        ./install/MacOs.sh 3.10
    - name: Unit Testing
      run: |
        ./test.sh

