name: Unit Tests on Win-Latest
run-name: ${{ github.actor }} Unit Testing on Ubuntu-Latest
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build310:
    runs-on: [self-hosted, windows]
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        ./install/Windows.cmd 3.10
    - name: Unit Testing
      run: |
        ./test.cmd

  build311:
    runs-on: [self-hosted, win]
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: |
        ./install/Windows.cmd 3.11
    - name: Unit Testing
      run: |
        ./test.cmd

